# Build settings
gems:
  - jemoji
  - jekyll-paginate

# Site settings
title: "Behind the Curtains: The Emotional Arcs of Cinema"
description: > # this means to ignore newlines until "email:"
   A Dataffoneurs Production: An Emotional Journey Through Cinema
   
   Please feel free to click on the first post and start the emotional ride!

email: a-mail@mail.mail
#blog logo
#logo: "/assets/images/df_logo.jpg"
float_logo: false # true, false (default) 
# how to remove the logo from the header and use the site title instead
logo: false


# blog cover
cover: "/assets/images/615i3d9LojL.jpg"
# how to show the image bigger in the header
cover_size: cover # contain (default), cover
#and how do I make it to not hide the cover when i gradually scroll down the page
cover_hide: false

name: 'DatAffoneurs'
author: 'DatAffoneurs'
#author_image: "/assets/images/author.jpg"
#how to remove the author image from the header
author_image: false

paginate:	5

url: "https://xavmarch13.github.io"
baseurl: "/dataffoneurs-story"
#used to display twitter cards
twitter_handle: '@dirkfabisch'
#how to remove the twitter handle from the header
twitter_handle: false

#fill in disqus shortname to use disqus
#disqus: disqus-shortname

#google_analytics: UA-XXXXX-X

# social icons and sharing options
social:
  - icon:	twitter
    url:	https://twitter.com/dirkfabisch
    desc: Follow me on twitter
    share_url: http://twitter.com/share
    share_title: ?text=
    share_link: "&amp;url="

#  - icon:	facebook
#    url:	https://facebook.com/???
#    desc: Connect with me facebook
#    share_url: https://www.facebook.com/sharer.php
#    share_title: ?t=
#    share_link: "&amp;u="

  - icon:	github
    url:	https://github.com/dirkfabisch
    desc:	Fork me on github
    share_url:
    share_title:
    share_link:

#  - icon:	google-plus
#    url:	https://google.com/???
#    desc:	Add me on google+
#    share_url:
#    share_title:
#    share_link:
# how to remove the social icons from the header
social: false
